apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::865051481474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14HBXDINSLWRL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::865051481474:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-29T10:15:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1671"
  uid: 93fff569-d647-4aba-8e3c-577ec0441c19
